name: Split

on:
  push:
    branches:
      - main

    # see https://github.community/t/how-to-run-github-actions-workflow-only-for-new-tags/16075/10?u=tomasvotruba
    tags:
      - '*'

  pull_request: null

  release:
    types: [created]

jobs:
  split:
    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@v2

      -
        # run action.yaml in the root directory
        # see https://github.community/t/self-reference-an-action-for-testing/17891
        uses: "./"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package_directory: 'packages/installer'
          repository_organization: 'HappyPHP'
          repository_name: 'installer'

          # change to use that should be signed under the split commit
          user_name: 'dluague'
          user_email: 'darwinluague9001@gmail.com'
      - # run action.yaml in the root directory
        # see https://github.community/t/self-reference-an-action-for-testing/17891
        uses: "./"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package_directory: 'packages/framework'
          repository_organization: 'HappyPHP'
          repository_name: 'framework'

          # change to use that should be signed under the split commit
          user_name: 'dluague'
          user_email: 'darwinluague9001@gmail.com'
